use_frameworks!

platform :ios, '9.0'

target 'TestTVPod_Example' do
  pod 'TestTVPod', :path => '../'

  target 'TestTVPod_Tests' do
    inherit! :search_paths
  end

  target 'TVApp' do
    inherit! :search_paths
  end

  target 'WatchAPP' do
    inherit! :search_paths
  end


end
